|<img src="https://drive.google.com/uc?id=1kjzJXxk2dJDr_oNKOqgGjBPbu4v-s0NW" width="100px" height="100">| <p> Métodos Cuantitativos</p> <p>Ingeniería en Control de Gestión</p> <p>Unidad I: Estadística y Probabilidades con Python</p> <p>Sesión 3: Introducción a la librería Pandas</p>|
|:--- |:---|

# **Pandas**

 Pandas es una biblioteca de Python que ofrece estructuras de datos y herramientas de análisis de datos poderosas y flexibles. Su principal objeto son los **DataFrames**, que son **estructuras tabulares bidimensionales con etiquetas en filas y columnas**.

 * Ésta librería combina el alto desempeño de operaciones vectorizadas de **numpy**
con las manipulaciones flexibles de hojas de cálculo y bases de datos relacionales.

* La convención para poder importar esta libreria es:

```python
import pandas as pd

```

* Siempre apoyarse en la documentación (https://pandas.pydata.org/docs/user_guide/index.html)

In [1]:
from IPython.display import IFrame
IFrame('https://pandas.pydata.org/docs/index.html', width=1000, height=400)

In [1]:
import pandas as pd

# **Crear Dataframes**

Puedes crear un DataFrame de varias maneras, pero una de las más comunes es a partir de un diccionario de listas o arrays NumPy

## **Desde Diccionarios**

In [3]:
# Se puede crear directamente desde un Diccionario de Listas o Arrays:
data = {'Nombre': ['Juan', 'Ana', 'Luis'],
        'Edad': [25, 30, 22],
        'Ciudad': ['Santiago', 'La Serena', 'Temuco']}

df = pd.DataFrame(data)
print(df)

  Nombre  Edad     Ciudad
0   Juan    25   Santiago
1    Ana    30  La Serena
2   Luis    22     Temuco

In [4]:
# hay un método específico para diccionarios (pd.DataFrame.from_dict) que funciona similar al normal, pero tiene mas opciones
data = {'Nombre': ['Juan', 'Ana', 'Luis'],
        'Edad': [25, 30, 22],
        'Ciudad': ['Santiago', 'La Serena', 'Temuco']}


df = pd.DataFrame.from_dict(data)
print(df)

  Nombre  Edad     Ciudad
0   Juan    25   Santiago
1    Ana    30  La Serena
2   Luis    22     Temuco

In [5]:
# Acá pd.DataFrame.from_dict permite que la orientación cambie y que en vez de tener
# índices numéricos tengamos los nombres de las variables

data = {'Nombre': ['Juan', 'Ana', 'Luis'],
        'Edad': [25, 30, 22],
        'Ciudad': ['Madrid', 'Barcelona', 'Valencia']}

# Usar el constructor from_dict con orientación 'index'
df = pd.DataFrame.from_dict(data, orient='index', columns=['Persona1', 'Persona2', 'Persona3'])
# acá cambiamos la orientación con orient y le asignamos nombres a las columnas (personas)
print(df)

       Persona1   Persona2  Persona3
Nombre     Juan        Ana      Luis
Edad         25         30        22
Ciudad   Madrid  Barcelona  Valencia

## **Desde Listas**

In [6]:
nombres = ['Juan', 'Ana', 'Luis']
edades = [25, 30, 22]

# Crear un DataFrame desde dos listas
df = pd.DataFrame({'Edad': edades, 'Nombre': nombres}) # Le pasamos un dicionario con el nombre de la columna:valor
print(df)

   Edad Nombre
0    25   Juan
1    30    Ana
2    22   Luis

In [7]:
data_list_of_lists = [['Juan', 25, 'Santiago'],
                      ['Ana', 30, 'La Serena'],
                      ['Luis', 22, 'Temuco']]

df = pd.DataFrame(data_list_of_lists, columns=['Nombre', 'Edad', 'Ciudad'])
print(df)

  Nombre  Edad     Ciudad
0   Juan    25   Santiago
1    Ana    30  La Serena
2   Luis    22     Temuco

# **Carga y lectura de dataframes**

Pandas ofrece la función `pd.read_*()` para cargar diferentes tipos de datos, como CSV, Excel, JSON, SQL, HTML, entre otros


* **Cargar desde CSV**:

```python
  data = pd.read_csv('archivo.csv')
```

* **Cargar desde Excel**:

```python
  data = pd.read_excel('archivo.xlsx', sheet_name='hoja1')
```

* **Cargar desde JSON**:

```python
  data = pd.read_json('archivo.json')
```

* **Cargar desde base de datos**:

```python
  datos_sql = pd.read_sql(consulta_sql, conexion)
```

**Parámetros de pd.read_*():**  

* **sep:** Especifica el delimitador en archivos CSV  Ejemplo (**, ;**)
* **header:** Indica qué fila se utiliza como encabezado (no siempre es la primera).
* **encoding:** Se especifica la codificación de caracteres que se utilizará al leer o escribir el archivo Ejemplo (**utf-8, latin-1,utf-16**) .
* **index_col:** Especifica qué columna se debe usar como índice.
* **dtype:** Define el tipo de datos de las columnas.
* **usecols:** Permite seleccionar un subconjunto de columnas para leer.
* **skiprows:** Permite saltar un número especificado de filas al comienzo del archivo.


Revisar documentación (https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)

In [2]:
df = pd.read_csv('https://drive.google.com/uc?id=1RJNg3-5dqTkzJrmfNETe6w_Aunv8TBL1')

### **Función head()**
 Está función permite mostrar las n primeras filas de un dataframe por defecto tiene un valor de 5 `head(n=5)`, pero se puede modificar al valor deseado

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### **Función tail()**
 Está función permite mostrar las n últimas filas de un dataframe por defecto tiene un valor de 5 `tail(n=5)`, pero se puede modificar al valor deseado

In [11]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

## **Carga desde local**

Para la siguiente sección, descarga el archivo `planetas.xlsx` desde el siguiente link: https://drive.google.com/uc?id=1amIKctJMgTD7CqBjH2qRQ2v2vqlThpmQ

In [13]:
# Utilizar sheet_name
df2 = pd.read_excel('planetas.xlsx', sheet_name = 'Imaging')

In [14]:
df2.head(2)

  Unnamed: 0      Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0     number  orbital_period       mass   distance       year
1          1             NaN        NaN      45.52       2005

In [15]:
# utilizar parametro header
df2 = pd.read_excel('planetas.xlsx', header=1, sheet_name='Imaging')
df2.head(10)

   number  orbital_period  mass  distance  year
0       1             NaN   NaN     45.52  2005
1       1             NaN   NaN    165.00  2007
2       1             NaN   NaN    140.00  2004
3       1             NaN   NaN       NaN  2008
4       1             NaN   NaN    145.00  2013
5       1             NaN   NaN    139.00  2004
6       1             NaN   NaN     18.39  2006
7       1          6000.0   NaN     19.28  2008
8       1             NaN   NaN     52.03  2012
9       1        318280.0   NaN      7.69  2008

## **Carga desde una tabla en internet**

`pd.read_html()` es una función en Pandas que se utiliza para leer tablas directamente desde páginas web. Esta función busca automáticamente las tablas HTML en una página y las carga en un DataFrame de Pandas.

Ejemplo: https://www.bbc.com/sport/football/premier-league/table

In [16]:
url = 'https://www.bbc.com/sport/football/premier-league/table'  # link a pagina web

# Utilizar pd.read_html() para leer las tablas HTML en la página
tablas = pd.read_html(url)

# Seleccionar la tabla correcta (en este caso, la primera tabla)
tabla_premier_league = tablas[0]
tabla_premier_league

,Position,Team,Played,Won,Drawn,Lost,Goals For,Goals Against,Goal Difference,Points,"Form, Last 6 games, Oldest first"
0,1,Liverpool,23,17,5,1,56,21,35,56,WResult WinDResult DrawDResult DrawWResult Win...
1,2,Arsenal,24,14,8,2,49,22,27,50,WResult WinDResult DrawWResult WinDResult Draw...
2,3,Nottingham Forest,24,14,5,5,40,27,13,47,WResult WinWResult WinDResult DrawWResult WinL...
3,4,Chelsea,24,12,7,5,47,31,16,43,LResult LossDResult DrawDResult DrawWResult Wi...
4,5,Manchester City,24,12,5,7,48,35,13,41,WResult WinWResult WinDResult DrawWResult WinW...
5,6,Newcastle United,24,12,5,7,42,29,13,41,WResult WinWResult WinWResult WinLResult LossW...
6,7,AFC Bournemouth,24,11,7,6,41,28,13,40,DResult DrawWResult WinDResult DrawWResult Win...
7,8,Aston Villa,24,10,7,7,34,37,-3,37,DResult DrawWResult WinWResult WinDResult Draw...
8,9,Fulham,24,9,9,6,36,32,4,36,DResult DrawDResult DrawLResult LossWResult Wi...
9,10,Brighton & Hove Albion,24,8,10,6,35,38,-3,34,DResult DrawDResult DrawWResult WinWResult Win...
10,11,Brentford,24,9,4,11,42,42,0,31,LResult LossWResult WinDResult DrawLResult Los...
11,12,Crystal Palace,24,7,9,8,28,30,-2,30,WResult WinDResult DrawWResult WinWResult WinL...
12,13,Manchester United,24,8,5,11,28,34,-6,29,LResult LossDResult DrawWResult WinLResult Los...
13,14,Tottenham Hotspur,24,8,3,13,48,37,11,27,DResult DrawLResult LossLResult LossLResult Lo...
14,15,West Ham United,24,7,6,11,29,46,-17,27,LResult LossLResult LossWResult WinLResult Los...
15,16,Everton,23,6,8,9,23,28,-5,26,LResult LossLResult LossLResult LossWResult Wi...
16,17,Wolverhampton Wanderers,24,5,4,15,34,52,-18,19,DResult DrawLResult LossLResult LossLResult Lo...
17,18,Leicester City,24,4,5,15,25,53,-28,17,LResult LossLResult LossLResult LossLResult Lo...
18,19,Ipswich Town,24,3,7,14,22,49,-27,16,WResult WinDResult DrawLResult LossLResult Los...
19,20,Southampton,24,2,3,19,18,54,-36,9,LResult LossLResult LossLResult LossLResult Lo...

Si Pandas no encuentra datos en tipo tabular para descargar, resultará en error

In [17]:
url = "https://unsplash.com/es/images/animals/kitten"

pd.read_html(url)

ValueError: No tables found

# **Descripcion básica dataframes**

Cuando trabajas con un DataFrame en Pandas, es útil obtener una descripción general de los datos. Algunos aspectos clave de esta descripción incluyen:

* **Dimensiones del DataFrame:** El número de filas y columnas en el DataFrame.

* **Tipos de Datos:** Los tipos de datos presentes en cada columna.

* **Valores No Nulos:** La cantidad de valores no nulos en cada columna.

* **Estadísticas Descriptivas:** Estadísticas resumidas para cada columna, como media, desviación estándar, mínimo, máximo, etc.

In [18]:
df = pd.read_csv('https://drive.google.com/uc?id=1RJNg3-5dqTkzJrmfNETe6w_Aunv8TBL1')

In [19]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

## **Tamaño del dataframe y nombre de las columnas**

In [20]:
df.shape # conociendo el tamaño del dataframe (FILAS, COLUMNAS)

(891, 12)

In [21]:
type(df.shape)

tuple

In [22]:
df.shape[0] # filas

891

In [23]:
df.shape[1] # columnas

12

In [24]:
# Proporciona información sobre las columnas del DataFrame
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

 El conjunto de datos del Titanic es un conjunto clásico utilizado en la ciencia de datos y contiene información sobre los pasajeros a bordo del famoso barco Titanic.

 Aquí está una descripción general de cada columna en el conjunto de datos del Titanic:

* **Survived:** Indica si el pasajero sobrevivió o no al hundimiento del Titanic. (0 = No, 1 = Sí)
* **Pclass**: Clase socioeconómica del pasajero. (1 = Primera clase, 2 = Segunda clase, 3 = Tercera clase)
* **Name**: Nombre del pasajero.
* **Sex**: Género del pasajero. (Male = Masculino, Female = Femenino)
* **Age**: Edad del pasajero en años.
* **SibSp**: Cantidad de hermanos/cónyuge a bordo del Titanic.
* **Parch**: Cantidad de padres/hijos a bordo del Titanic.
* **Ticket**: Número del ticket.
* **Fare**: Tarifa pagada por el pasajero.
* **Cabin**: Número de la cabina del pasajero.
* **Embarked**: Puerto de embarque del pasajero. (C = Cherbourg, Q = Queenstown, S = Southampton)

## **Tipos de datos y estadísticas básicas**

In [25]:
# Proporciona una descripción concisa del DataFrame, incluidos los tipos de datos y la cantidad de valores no nulos.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [26]:
# Si solo queremos el tipo de datos
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [27]:
#  Calcula estadísticas descriptivas para columnas numéricas, como media, desviación estándar, mínimo, máximo y cuartiles.
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [28]:
df.describe(percentiles=[0.1, 0.4, 0.9, 0.95]) # se pueden cambiar los percentiles

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
10%,90.000000,0.000000,1.000000,14.000000,0.000000,0.000000,7.550000
40%,357.000000,0.000000,2.000000,25.000000,0.000000,0.000000,10.500000
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
90%,802.000000,1.000000,3.000000,50.000000,1.000000,2.000000,77.958300
95%,846.500000,1.000000,3.000000,56.000000,3.000000,2.000000,112.079150
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [29]:
df.describe(include="all")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,B96 B98,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

##**Conteo de elementos diferentes en una columna**

El método `value_counts()` en Pandas se utiliza para contar la ocurrencia de valores únicos en una Serie. Este método proporciona información sobre la distribución de valores y la frecuencia de cada valor único en una columna.

```python
serie.value_counts(normalize=False, sort=True, ascending=False, bins=None, dropna=True)

```

* **normalize:** Si es `True`, devuelve las frecuencias relativas en lugar de las frecuencias absolutas. Por defecto, es `False`.
* **sort:** Si es `True`, ordena los resultados por frecuencia. Por defecto, es True.
* **ascending:** Si es `True`, ordena las frecuencias en orden ascendente. Por defecto, es `False`.
* **bins:** Solo para datos numéricos. Divide los valores en intervalos y cuenta la frecuencia en cada intervalo.
*  **dropna:** Si es `False`, incluye los valores nulos en el resultado. Por defecto, es `True`.

In [30]:
type(df)

pandas.core.frame.DataFrame

In [31]:
type(df["PassengerId"])

pandas.core.series.Series

In [32]:
df["Sex"]

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: object

In [33]:
frecuencia_genero = df['Sex'].value_counts()
frecuencia_genero

Sex
male      577
female    314
Name: count, dtype: int64

In [34]:
frecuencia_genero = df['Sex'].value_counts(normalize=True) # acá lo entrega en porcentajes o normalizados (0-1)
frecuencia_genero

Sex
male      0.647587
female    0.352413
Name: proportion, dtype: float64

In [35]:
frecuencia_genero = df['Sex'].value_counts(normalize= True, ascending=True)  # Lo entrega en forma ascendente
frecuencia_genero

Sex
female    0.352413
male      0.647587
Name: proportion, dtype: float64

In [36]:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [37]:
frecuencia_precio_ticket = df['Age'].value_counts(bins=5) # aca al ser variable numérica le entregamos una cantidad de bins (grupos)
frecuencia_precio_ticket

(16.336, 32.252]    346
(32.252, 48.168]    188
(0.339, 16.336]     100
(48.168, 64.084]     69
(64.084, 80.0]       11
Name: count, dtype: int64

## **Ordenamiento del dataframe**
* Para ordenar el dataframe se utiliza

```python
df.sort_values('columna')
```
* Por defecto ordena de menor a mayor (ascending = True), si se quiere ordenar de mayor a menor:

```python
df.sort_values('columna', ascending = False)
```
* Si se quiere perpetuar este orden se puede agregar el inplace = True:
o asignarlo a df

```python
df.sort_values('columna', ascending = False, inplace = True)
df = df.sort_values('columna', ascending = False)
```

* Se pueden ordenar por múltiples columnas: Pasando en una lista el orden de columnas por las que se quieren ordenar y una lista con la forma de ordenar de mayor a menor o viceversa.

```python
df.sort_values(['columna1', 'columna2'], ascending = [True or False, True or False], inplace = True)
```

Más detalles en: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html

In [38]:
# Ordenando por el precio del ticket
df.sort_values('Fare', ascending=False).head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,19950,263.0000,C23 C25 C27,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
311,312,1,1,"Ryerson, Miss. Emily Borie",female,18.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
742,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C

Al consultar nuevamente el DataFrame, podemos observar que los cambios no se realizaron de manera permanente.

In [39]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [40]:
# Vamos ordenar por la edad el dataframe df
df.sort_values('Age', ascending = False, inplace = True)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q

In [41]:
# Ordenando por el precio del ticket de forma descendente y años por forma ascendente
df.sort_values(['Fare', 'Age'], ascending=[False, True], inplace=True)
df.head()

## Observar que los índices tienen valores de acuerdo a la posición del dataframe original

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S

## **Restablecer el Índice en un DataFrame**

Al trabajar con **DataFrames** en Pandas, ciertas operaciones pueden modificar el índice. La función `reset_index()` permite restaurar el índice a su estado predeterminado o generar uno nuevo.

<h3><b>Uso básico</b></h3>

```python
df.reset_index()
```

**Parámetros opcionales**

* **inplace:** Este parámetro, si se establece en **True**, modifica el DataFrame existente y no devuelve uno nuevo. **Por defecto, es False**.

* **drop:** Si se establece en **True**, elimina la columna del índice existente y no la incluye como una nueva columna en el DataFrame resultante. **Por defecto, es False**.

In [42]:
df.reset_index(inplace=True, drop=True)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
1,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
2,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
3,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
4,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S

In [43]:
df["Name"]

0                  Lesurer, Mr. Gustave J
1                        Ward, Miss. Anna
2      Cardeza, Mr. Thomas Drake Martinez
3          Fortune, Mr. Charles Alexander
4              Fortune, Miss. Mabel Helen
                      ...
886      Frost, Mr. Anthony Wood "Archie"
887         Parr, Mr. William Henry Marsh
888            Watson, Mr. Ennis Hastings
889                  Knight, Mr. Robert J
890                      Fry, Mr. Richard
Name: Name, Length: 891, dtype: object

## **Crear columnas**

En pandas, el concepto de crear columnas en un DataFrame se refiere a agregar nuevas series de datos al DataFrame existente.

### **Creando una columna con un valor fijo**

In [44]:
df['Fecha'] = '2023-01-01'  # le da un mismo valor a toda la columna
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fecha
0,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,2023-01-01
1,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,2023-01-01
2,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,2023-01-01
3,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,2023-01-01
4,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S,2023-01-01

### **Creando una columna con un valor distinto**

Le podemos pasar un valor diferente para cada fila ya sea con una lista como un array

In [45]:
df.shape

(891, 13)

In [46]:
import random
numeros_al_azar = [random.randint(1, 100) for i in range(df.shape[0])]
len(numeros_al_azar)

891

In [47]:
df['Num_azar'] = numeros_al_azar

In [48]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fecha,Num_azar
0,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,2023-01-01,46
1,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,2023-01-01,81
2,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,2023-01-01,10
3,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,2023-01-01,73
4,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S,2023-01-01,11

### **Creando una columna mediante operaciones de columnas**

Se puede generar una nueva mediante una operación entre dos o mas columnas existentes

In [49]:
# haciendo operaciones entre columnas numéricas
df['ID_CLASS'] = df["PassengerId"] + df["Survived"]
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fecha,Num_azar,ID_CLASS
0,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,2023-01-01,46,739
1,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,2023-01-01,81,260

In [50]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
Fecha           object
Num_azar         int64
ID_CLASS         int64
dtype: object

In [51]:
# haciendo operaciones entre columnas strings
df['NAME_SEX'] = df["Name"] + '_' + df["Sex"]
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fecha,Num_azar,ID_CLASS,NAME_SEX
0,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,2023-01-01,46,739,"Lesurer, Mr. Gustave J_male"
1,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,2023-01-01,81,260,"Ward, Miss. Anna_female"

In [52]:
# haciendo operaciones entre columnas strings y numéricas
df['AGE_SEX'] = df["Age"].astype(str) + '_' + df["Sex"]
# se necesita transformar la columna numérica a string para poder concatenar

"""
Si necesitamos hacer una operación matemática con una columna string debemos transformar
(si se puede) a int o float previo a la operación
"""

df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fecha,Num_azar,ID_CLASS,NAME_SEX,AGE_SEX
0,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,2023-01-01,46,739,"Lesurer, Mr. Gustave J_male",35.0_male
1,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,2023-01-01,81,260,"Ward, Miss. Anna_female",35.0_female

#**Elementos nulos**
En Pandas, hay varios métodos y funciones relacionadas con la gestión de valores nulos (NaN) en DataFrames y Series

## **isna() , isnull(), notna(), notnull()**

* **isna() y isnull()**
Estos métodos devuelven una máscara booleana indicando dónde se encuentran los valores nulos.

* **notna() y notnull()**
Estos métodos son lo opuesto a isna() y isnull(), devuelven una máscara booleana indicando dónde NO se encuentran los valores nulos.

In [53]:
df.isna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fecha,Num_azar,ID_CLASS,NAME_SEX,AGE_SEX
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False
887,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False
889,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False
890,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False

In [54]:
df.notna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fecha,Num_azar,ID_CLASS,NAME_SEX,AGE_SEX
0,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,True,True,True,True,True,False,True,True,True,True,False,True,True,True,True,True,True
887,True,True,True,True,True,False,True,True,True,True,False,True,True,True,True,True,True
888,True,True,True,True,True,False,True,True,True,True,False,True,True,True,True,True,True
889,True,True,True,True,True,False,True,True,True,True,False,True,True,True,True,True,True
890,True,True,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True

In [55]:
df.isna().sum() # Podemos ver la suma de elementos perdidos por columna

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
Fecha            0
Num_azar         0
ID_CLASS         0
NAME_SEX         0
AGE_SEX          0
dtype: int64

In [56]:
df.notna().sum() # Podemos ver la suma de elementos completos por columna

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
Fecha          891
Num_azar       891
ID_CLASS       891
NAME_SEX       891
AGE_SEX        891
dtype: int64

##**Eliminar registros nulos dropna()**

El método `dropna() `en Pandas se utiliza para eliminar filas o columnas que contienen valores nulos (**NaN**) de un DataFrame. Este método ofrece flexibilidad para adaptarse a diferentes necesidades de limpieza de datos.

```python
df.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)

```

* **axis:** Especifica si se eliminarán **filas (axis=0)** o **columnas (axis=1)**. Por defecto, es 0 (filas).
* **how:** Controla cuándo se eliminará una fila o columna. Puede ser '**any**' (si hay al menos un NaN) o '**all**' (solo si todos son NaN). Por defecto, es 'any'.
* **thresh:** Número mínimo de valores no nulos necesarios para que una fila o columna no sea eliminada.
* **subset:** Lista de etiquetas de índice o nombres de columnas en los cuales buscar valores nulos.
* **inplace:** Si es `True`, realiza la eliminación en el lugar y modifica el DataFrame original. Por defecto, es `False`

In [57]:
print(df.shape) # Tamaño original (891, 12)

(891, 17)

In [58]:
df2 = df.dropna()
print(df2.shape)

(183, 17)

In [59]:
df3 = df.dropna(subset=['Age'])  # Sólo eliminamos donde Age es nulo (714, 12)
print(df3.shape)

(714, 17)

##**Reemplazando los registros nulos fillna()**

El método `.fillna()` en Pandas se utiliza para rellenar los valores nulos (`NaN`) en un DataFrame o una Serie con valores específicos o mediante ciertos métodos de interpolación. La idea principal es no perder registros valiosos.

```python
df.fillna(value=None, method=None, axis=None, inplace=False, limit=None, downcast=None)
```

<h3><b>Algunos parámetros:</h3></b>

* **value:** Valor escalar, diccionario o Series que indica qué valor usar para rellenar NaN. Por defecto, es None.
* **method:** Método de rellenado, como **'ffill' (forward fill)** o '**bfill' (backward fill)**. Por defecto, es None.
* **axis:** Eje a lo largo del cual se realizará el rellenado (0 para filas, 1 para columnas). Por defecto, es None (rellenado en ambos ejes).
* **inplace:** Si es `True`, realiza el rellenado en el lugar y devuelve None. Por defecto, es `False`.

In [60]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
Fecha            0
Num_azar         0
ID_CLASS         0
NAME_SEX         0
AGE_SEX          0
dtype: int64

In [61]:
df4 = df.fillna(0)
df4.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
Fecha          0
Num_azar       0
ID_CLASS       0
NAME_SEX       0
AGE_SEX        0
dtype: int64

In [62]:
df4.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fecha,Num_azar,ID_CLASS,NAME_SEX,AGE_SEX
0,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,2023-01-01,46,739,"Lesurer, Mr. Gustave J_male",35.0_male
1,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,0,C,2023-01-01,81,260,"Ward, Miss. Anna_female",35.0_female
2,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,2023-01-01,10,681,"Cardeza, Mr. Thomas Drake Martinez_male",36.0_male
3,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,2023-01-01,73,28,"Fortune, Mr. Charles Alexander_male",19.0_male
4,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S,2023-01-01,11,90,"Fortune, Miss. Mabel Helen_female",23.0_female

In [63]:
df.tail(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fecha,Num_azar,ID_CLASS,NAME_SEX,AGE_SEX
886,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,239854,0.0,NaN,S,2023-01-01,77,482,"Frost, Mr. Anthony Wood ""Archie""_male",nan_male
887,634,0,1,"Parr, Mr. William Henry Marsh",male,NaN,0,0,112052,0.0,NaN,S,2023-01-01,89,634,"Parr, Mr. William Henry Marsh_male",nan_male
888,675,0,2,"Watson, Mr. Ennis Hastings",male,NaN,0,0,239856,0.0,NaN,S,2023-01-01,88,675,"Watson, Mr. Ennis Hastings_male",nan_male
889,733,0,2,"Knight, Mr. Robert J",male,NaN,0,0,239855,0.0,NaN,S,2023-01-01,64,733,"Knight, Mr. Robert J_male",nan_male
890,816,0,1,"Fry, Mr. Richard",male,NaN,0,0,112058,0.0,B102,S,2023-01-01,83,816,"Fry, Mr. Richard_male",nan_male

In [64]:
df5 = df.ffill()  # rellena con el valor no nulo que esta arriba  --->
df5.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fecha,Num_azar,ID_CLASS,NAME_SEX,AGE_SEX
0,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,2023-01-01,46,739,"Lesurer, Mr. Gustave J_male",35.0_male
1,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,B101,C,2023-01-01,81,260,"Ward, Miss. Anna_female",35.0_female
2,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,2023-01-01,10,681,"Cardeza, Mr. Thomas Drake Martinez_male",36.0_male
3,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,2023-01-01,73,28,"Fortune, Mr. Charles Alexander_male",19.0_male
4,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S,2023-01-01,11,90,"Fortune, Miss. Mabel Helen_female",23.0_female
5,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,19950,263.0000,C23 C25 C27,S,2023-01-01,67,343,"Fortune, Miss. Alice Elizabeth_female",24.0_female
6,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S,2023-01-01,79,439,"Fortune, Mr. Mark_male",64.0_male
7,312,1,1,"Ryerson, Miss. Emily Borie",female,18.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,2023-01-01,84,313,"Ryerson, Miss. Emily Borie_female",18.0_female
8,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,2023-01-01,60,744,"Ryerson, Miss. Susan Parker ""Suzette""_female",21.0_female
9,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C,2023-01-01,5,119,"Baxter, Mr. Quigg Edmond_male",24.0_male

In [65]:
df6 = df.bfill()  # rellena con el valor que está abajo  <---
df6.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fecha,Num_azar,ID_CLASS,NAME_SEX,AGE_SEX
0,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,2023-01-01,46,739,"Lesurer, Mr. Gustave J_male",35.0_male
1,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,B51 B53 B55,C,2023-01-01,81,260,"Ward, Miss. Anna_female",35.0_female
2,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,2023-01-01,10,681,"Cardeza, Mr. Thomas Drake Martinez_male",36.0_male
3,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,2023-01-01,73,28,"Fortune, Mr. Charles Alexander_male",19.0_male
4,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S,2023-01-01,11,90,"Fortune, Miss. Mabel Helen_female",23.0_female
5,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,19950,263.0000,C23 C25 C27,S,2023-01-01,67,343,"Fortune, Miss. Alice Elizabeth_female",24.0_female
6,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S,2023-01-01,79,439,"Fortune, Mr. Mark_male",64.0_male
7,312,1,1,"Ryerson, Miss. Emily Borie",female,18.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,2023-01-01,84,313,"Ryerson, Miss. Emily Borie_female",18.0_female
8,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,2023-01-01,60,744,"Ryerson, Miss. Susan Parker ""Suzette""_female",21.0_female
9,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C,2023-01-01,5,119,"Baxter, Mr. Quigg Edmond_male",24.0_male

In [66]:
df7 = df.copy()

In [67]:
df7["Age"].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [68]:
df["Age"].isna().sum()

177

In [69]:
# Rellenar con el promedio de la columna
df7['Age'].fillna(df7['Age'].mean(), inplace=True)
df7['Age'].describe()

<ipython-input-69-09fca5f6860f>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df7['Age'].fillna(df7['Age'].mean(), inplace=True)

count    891.000000
mean      29.699118
std       13.002015
min        0.420000
25%       22.000000
50%       29.699118
75%       35.000000
max       80.000000
Name: Age, dtype: float64

# **Eliminar columnas**

En pandas, el concepto de crear columnas en un DataFrame se refiere a eliminar una o más series de datos del DataFrame existente.

El método `drop` se utiliza para eliminar columnas o filas de un DataFrame. Cuando se usa para eliminar columnas, se especifica el parámetro `axis=1`.

```python
dataframe.drop(labels, axis=1, inplace=False)
```

* **labels:** Puede ser el nombre de una columna o una lista de nombres de columnas que deseas eliminar.

* **axis:** Debe ser establecido en 1 para indicar que estás eliminando columnas. Si quisieras eliminar filas, usarías axis=0.

* **inplace:** Un parámetro opcional que, si se establece en `True`, realizará la modificación en el lugar (es decir, **modificará el DataFrame original**). Si se establece en `False` **(valor predeterminado), devolverá un nuevo DataFrame con las columnas eliminadas**.

* **errors:** Determina que sucede si se le pasa una columna que no existe en el dataframe. Por defecto el valor es **'raise'**, generando error si no encuentra la columna y cayendo el programa. Pero se le puede pasar el valor **'ignore'** que no generar un error (evita que caiga el programa).

In [70]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Fecha', 'Num_azar',
       'ID_CLASS', 'NAME_SEX', 'AGE_SEX'],
      dtype='object')

In [71]:
# elimina columnas no deseadas
df.drop(columns = ['Num_azar', 'ID_CLASS', 'NAME_SEX', 'AGE_SEX',
                   'no_existe'], inplace = True, errors='ignore')

# sólo dejamos Fecha y agregamos una columna inexistente ('no_existe')

In [72]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Fecha'],
      dtype='object')

# **Renombrar columnas**

El método `rename()` se utiliza para cambiar el nombre de una columna o índice en un DataFrame.

```python
dataframe.rename(columns={'nombre_antiguo': 'nombre_nuevo'}, inplace=False)
```

* **columns:** Un diccionario que mapea los nombres de las columnas antiguas a los nuevos nombres. Puedes proporcionar tantos pares clave-valor como desees.
* **inplace:** Un parámetro opcional que, si se establece en `True`, realizará la modificación en el lugar (es decir, modificará el DataFrame original). Si se establece en `False` (**valor predeterminado**), devolverá un nuevo DataFrame con los nombres de las columnas cambiados.
* **errors:** Al igual con `drop()` , el valor predeterminado es **raise**, pero es preferible definirlo como **ignore**

In [73]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Fecha'],
      dtype='object')

In [74]:
df.rename(columns= {'Fecha':'Date', 'no_existe':'nuevo'}, inplace=True, errors='ignore')
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Date'],
      dtype='object')

In [75]:
# eliminamos Date
df.drop(columns=['Date'], inplace=True, errors='ignore')

# **Subsetting DataFrames**
Se refiere a la tarea de seleccionar y extraer un conjunto específico de datos de un DataFrame en base a ciertos criterios.

## **Selección de una Columna en un DataFrame**

Seleccionar una columna en un **DataFrame** de Pandas es una operación fundamental en el análisis de datos. Existen diferentes formas de hacerlo, y a continuación exploramos los métodos más utilizados.

### **1. Uso de Corchetes (`[]`)**
Este es el método más versátil, ya que permite seleccionar columnas incluso cuando sus nombres contienen **espacios o caracteres especiales**.

```python
df["NombreDeColumna"]
df["Columna con Espacios"]
```
### **2. Notación de Puntos (`.`)**:

Se puede acceder a una columna como si fuera un atributo del DataFrame, siempre que el nombre de la columna sea un identificador válido en Python (sin espacios, números al inicio o caracteres especiales).

```python
df.NombreDeColumna
df.Columna con Espacios  # generar error
```

In [76]:
years = df['Age']
years.head()

0    35.0
1    35.0
2    36.0
3    19.0
4    23.0
Name: Age, dtype: float64

In [77]:
nombres = df.Name
nombres.tail()

886    Frost, Mr. Anthony Wood "Archie"
887       Parr, Mr. William Henry Marsh
888          Watson, Mr. Ennis Hastings
889                Knight, Mr. Robert J
890                    Fry, Mr. Richard
Name: Name, dtype: object

## **Operaciones en una Columna o Serie**

En Pandas, cada columna de un **DataFrame** es una **Serie (`pd.Series`)**, lo que permite realizar diversas operaciones para manipular, analizar y visualizar datos. A continuación, se presentan algunas de las operaciones más comunes que pueden aplicarse a una columna o Serie.

### **Operaciones Aritméticas y Estadísticas**

`serie.mean(), serie.sum(), serie.max(), serie.min()`, etc.

In [78]:
years.mean() # Estas son series del dataframe y podemos realizar cálculos con ellos

29.69911764705882

In [79]:
years.max()

80.0

In [80]:
years.min()

0.42

In [81]:
years.describe() # acá podemos obtener el resumen , recordar que modificar los percentiles que deseemos con parámetro percentiles ej percentiles= [0.1,.9]

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [82]:
years.isnull().sum()  # Podemos ver los valores nulos

177

In [83]:
df["Pclass"]

0      1
1      1
2      1
3      1
4      1
      ..
886    2
887    1
888    2
889    2
890    1
Name: Pclass, Length: 891, dtype: int64

In [84]:
df['Pclass'].value_counts() # Podemos ver la cantidad de elementos en variables categóricas

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

## **Filtrado y Selección con Corchetes (`[]`)**

### **1. Selección de Columnas**
La **notación de corchetes (`[]`)** es una forma sencilla y flexible de acceder a columnas en un **DataFrame** de Pandas. Permite seleccionar una columna específica escribiendo su nombre entre corchetes:

```python
df["Columna"]
```

### **2. Filtrado de Datos con Condiciones**

También puedes usar la notación de corchetes para **filtrar filas** con condiciones sobre una columna. La expresión dentro de los corchetes debe evaluar a un conjunto de valores booleanos (`True` o `False`).

**Ejemplo: Filtrar valores mayores a un umbral**
```python
df[df["Columna"] > valor]
```

In [85]:
years.head()

0    35.0
1    35.0
2    36.0
3    19.0
4    23.0
Name: Age, dtype: float64

In [86]:
"ACÁ SOLO TENDREMOS UNA SERIE CON VALORES BOOLEANOS".capitalize()

'Acá solo tendremos una serie con valores booleanos'

In [87]:
# Acá solo tendremos una serie con valores booleanos True or False
# de acuerdo a si se cumple la condición
print(years > 18)

0       True
1       True
2       True
3       True
4       True
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [88]:
years[years > 18]

0      35.0
1      35.0
2      36.0
3      19.0
4      23.0
       ...
878    36.0
879    38.0
880    39.0
881    40.0
882    49.0
Name: Age, Length: 575, dtype: float64

In [89]:
# Al encerrar en df[condicion booleana] generamos un subset del array que cumple esa condición
anios_mayores = years[years>18]
print(anios_mayores.shape)
anios_mayores.head()

(575,)

0    35.0
1    35.0
2    36.0
3    19.0
4    23.0
Name: Age, dtype: float64

In [90]:
# Acá solo tendremos una serie con valores booleanos True or False se acuerdo a si se cumple la condición
df['Age'] < 18

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [91]:
"AL ENCERRAR EN df[CONDICION BOOELEANA] GENERAMOS UN SUBSET DEL DATAFRAME QUE CUMPLE ESA CONDICIÓN".capitalize()

'Al encerrar en df[condicion booeleana] generamos un subset del dataframe que cumple esa condición'

In [92]:
# Al encerrar en df[condicion booeleana] generamos un subset del dataframe que cumple esa condición
menores_edad = df[df['Age'] <18]
menores_edad.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
17,690,1,1,"Madill, Miss. Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S
25,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
26,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
38,803,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
39,436,1,1,"Carter, Miss. Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S

## **Método `query()`**

El método `query()` ofrece una forma más **expresiva y legible** para filtrar datos en Pandas. Su sintaxis es similar a las consultas en SQL, lo que facilita la escritura de condiciones de filtrado de manera más clara y concisa.

### **Ventajas del Método `query()`**
- Mejora la **legibilidad** del código al evitar el uso excesivo de corchetes y operadores lógicos.  
- Permite escribir condiciones en **formato de cadena de texto**, haciendo que el código sea más intuitivo.  
- Es especialmente útil cuando se trabaja con **columnas cuyos nombres contienen espacios**.  

### **Sintaxis**
```python
df.query("Condición")
```

In [93]:
mayores_edad = df.query('Age > 18')
mayores_edad.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
1,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
2,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
3,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
4,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S

## **Seleccionando en base a texto**

In [94]:
mujeres = df[df["Sex"] == 'female']
print(mujeres.shape)

(314, 12)

In [95]:
mujeres.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
4,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S

In [96]:
mujeres = df.query("Sex == 'female'")
print(mujeres.shape)

(314, 12)

In [97]:
mujeres.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
4,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S

## **Seleccionando múltiples columnas**

In [98]:
anios_sobrevivencia = df[['Age','Survived', 'Pclass']]
anios_sobrevivencia.head()

    Age  Survived  Pclass
0  35.0         1       1
1  35.0         1       1
2  36.0         1       1
3  19.0         0       1
4  23.0         1       1

## **Seleccionando basado en condiciones múltiples**

In [99]:
mujeres_primera_clase = df[
    (df["Sex"] == 'female') &
     (df["Pclass"]==1)
]
print(mujeres_primera_clase.shape)
mujeres_primera_clase.head()

(94, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
4,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
5,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,19950,263.0000,C23 C25 C27,S
7,312,1,1,"Ryerson, Miss. Emily Borie",female,18.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
8,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C

In [100]:
mujeres_primera_clase_query = df.query("Sex == 'female' and Pclass == 1")
print(mujeres_primera_clase_query.shape)
mujeres_primera_clase_query.head()

(94, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
4,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
5,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,19950,263.0000,C23 C25 C27,S
7,312,1,1,"Ryerson, Miss. Emily Borie",female,18.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
8,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C

## **Seleccionando basado en isin()**

In [101]:
df['Pclass'].value_counts() # seleccionemos sólo los que pertenecen a la primera y segunda clase

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [102]:
hombres_primerasegunda_clase = df[
    (df["Sex"] == 'male') &
     (df["Pclass"].isin([1,2]))
]
print(hombres_primerasegunda_clase.shape)
hombres_primerasegunda_clase.tail(10)

(230, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
880,807,0,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0,A36,S
881,264,0,1,"Harrison, Mr. William",male,40.0,0,0,112059,0.0,B94,S
883,278,0,2,"Parkes, Mr. Francis ""Frank""",male,NaN,0,0,239853,0.0,NaN,S
884,414,0,2,"Cunningham, Mr. Alfred Fleming",male,NaN,0,0,239853,0.0,NaN,S
885,467,0,2,"Campbell, Mr. William",male,NaN,0,0,239853,0.0,NaN,S
886,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,239854,0.0,NaN,S
887,634,0,1,"Parr, Mr. William Henry Marsh",male,NaN,0,0,112052,0.0,NaN,S
888,675,0,2,"Watson, Mr. Ennis Hastings",male,NaN,0,0,239856,0.0,NaN,S
889,733,0,2,"Knight, Mr. Robert J",male,NaN,0,0,239855,0.0,NaN,S
890,816,0,1,"Fry, Mr. Richard",male,NaN,0,0,112058,0.0,B102,S

In [103]:
hombres_primerasegunda_clase_query = df.query("Sex == 'male' and Pclass in [1, 2]")
print(hombres_primerasegunda_clase_query.shape)
hombres_primerasegunda_clase_query.head()

(230, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
2,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
3,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
6,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
9,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C

# **Agrupando Data**

La agrupación de datos con Pandas es una técnica poderosa para analizar conjuntos de datos mediante la segmentación de datos en grupos basados en determinados criterios. Esto implica:

- **Splitting** (División): Separar los datos en grupos basados en un criterio especificado.
- **Applying** (Aplicación): Aplicar una función a cada grupo independientemente.
- **Combining** (Combinación): Combinar los resultados en una estructura de datos.

* Pandas ofrece la función `groupby()` que permite realizar estas operaciones de manera eficiente. Se utiliza para dividir los datos en grupos basados en una columna específica o una serie de columnas. Luego, se pueden aplicar operaciones (como sumas, promedios, conteos, etc.) a estos grupos.


```python
df.groupby('VarCategorica')

df.groupby(['VarCategorica1', 'VarCategorica2']) # se pueden agrupar por varias
```


**Principales funciones**

* **groupby()**: Método para crear un objeto GroupBy.
* **agg()**: Para realizar agregaciones sobre grupos (por ejemplo, sumas, promedios, conteos).
* **apply()**: Para aplicar funciones personalizadas a grupos de datos.
* **transform()**: Para realizar transformaciones en los datos de cada grupo.
* **size()**: Para obtener el tamaño de cada grupo.
* **first(), last():** Para obtener el primer o último elemento de cada grupo.
* **describe()**: Para obtener estadísticas descriptivas por grupo.
* **filter()**: Para filtrar datos en función de propiedades de los grupos, retornando solo los registros en los que ciertos grupos cumplen la condición.

In [104]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
1,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C

In [105]:
# Agrupar por la clase
grouped = df.groupby('Pclass')
grouped  # el groupby es un tipo de dato , pero que no devuelve nada a menos que apliquemos una función

In [106]:
print(dir(grouped))

['Age', 'Cabin', 'Embarked', 'Fare', 'Name', 'Parch', 'PassengerId', 'Pclass', 'Sex', 'SibSp', 'Survived', 'Ticket', '_DataFrameGroupBy__examples_dataframe_doc', '__annotations__', '__class__', '__class_getitem__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__orig_bases__', '__parameters__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_accessors', '_agg_examples_doc', '_agg_general', '_agg_py_fallback', '_aggregate_frame', '_aggregate_with_numba', '_apply_filter', '_apply_to_column_groupbys', '_ascending_count', '_choose_path', '_concat_objects', '_constructor', '_cumcount_array', '_cython_agg_general', '_cython_transform', '_define_paths', '_deprecate_axis', '_descending_count', '_dir_additions', '_dir_deletions', '_fill', '_get_data_to_aggregate', '_get_index', '_get_indices', '_gotitem', '_grouper', '_hidden_attrs', '_idxmax_idxmin', '_infer_selection', '_insert_inaxis_grouper', '_internal_names', '_internal_names_set', '_is_protocol', '_make_mask_from_int', '_make_mask_from_list', '_make_mask_from_positional_indexer', '_make_mask_from_slice', '_make_mask_from_tuple', '_mask_selected_obj', '_maybe_transpose_result', '_nth', '_numba_agg_general', '_numba_prep', '_obj_1d_constructor', '_obj_with_exclusions', '_op_via_apply', '_positional_selector', '_python_agg_general', '_python_apply_general', '_reindex_output', '_reset_cache', '_selected_obj', '_selection', '_selection_list', '_set_result_index_ordered', '_transform', '_transform_general', '_transform_with_numba', '_value_counts', '_wrap_agged_manager', '_wrap_aggregated_output', '_wrap_applied_output', '_wrap_applied_output_series', '_wrap_idxmax_idxmin', '_wrap_transform_fast_result', 'agg', 'aggregate', 'all', 'any', 'apply', 'bfill', 'boxplot', 'corr', 'corrwith', 'count', 'cov', 'cumcount', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'dtypes', 'ewm', 'expanding', 'ffill', 'fillna', 'filter', 'first', 'get_group', 'groups', 'head', 'hist', 'idxmax', 'idxmin', 'indices', 'last', 'max', 'mean', 'median', 'min', 'ndim', 'ngroup', 'ngroups', 'nth', 'nunique', 'ohlc', 'pct_change', 'pipe', 'plot', 'prod', 'quantile', 'rank', 'resample', 'rolling', 'sample', 'sem', 'shift', 'size', 'skew', 'std', 'sum', 'tail', 'take', 'transform', 'value_counts', 'var']

### **size()**

El métodos size Entrega un Conteo de la cantidad de elementos para cada grupo disponible.

In [107]:
conteo = grouped.size()   # sacando la cantidad de registros para cada clase
conteo

Pclass
1    216
2    184
3    491
dtype: int64

### **first()  y last()**

Estos métodos son dimilares al head() o tail(), pero nos entregan ya sea el primero(first) o último(last) de los registros de cada grupo

In [108]:
grouped.first()

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Pclass,,,,,,,,,,,
1,738,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
2,386,0,"Davies, Mr. Charles Henry",male,18.0,0,0,S.O.C. 14879,73.5000,F4,S
3,160,0,"Sage, Master. Thomas Henry",male,26.0,8,2,CA. 2343,69.5500,F E69,S

In [109]:
grouped.last()

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Pclass,,,,,,,,,,,
1,816,0,"Fry, Mr. Richard",male,40.0,0,0,112058,0.0,B102,S
2,733,0,"Knight, Mr. Robert J",male,70.0,0,0,239855,0.0,E77,S
3,598,0,"Johnson, Mr. Alfred",male,49.0,0,0,LINE,0.0,F G63,S

### **describe()**

El métodos describe Entrega un Resumen Estadístico de los grupos disponibles.

In [110]:
grouped.describe().T # Permite realizar una descripción  de als variables numéricas de cada grupo

Pclass                      1           2           3
PassengerId count  216.000000  184.000000  491.000000
            mean   461.597222  445.956522  439.154786
            std    246.737616  250.852161  264.441453
            min      2.000000   10.000000    1.000000
            25%    270.750000  234.500000  200.000000
            50%    472.000000  435.500000  432.000000
            75%    670.500000  668.000000  666.500000
            max    890.000000  887.000000  891.000000
Survived    count  216.000000  184.000000  491.000000
            mean     0.629630    0.472826    0.242363
            std      0.484026    0.500623    0.428949
            min      0.000000    0.000000    0.000000
            25%      0.000000    0.000000    0.000000
            50%      1.000000    0.000000    0.000000
            75%      1.000000    1.000000    0.000000
            max      1.000000    1.000000    1.000000
Age         count  186.000000  173.000000  355.000000
            mean    38.233441   29.877630   25.140620
            std     14.802856   14.001077   12.495398
            min      0.920000    0.670000    0.420000
            25%     27.000000   23.000000   18.000000
            50%     37.000000   29.000000   24.000000
            75%     49.000000   36.000000   32.000000
            max     80.000000   70.000000   74.000000
SibSp       count  216.000000  184.000000  491.000000
            mean     0.416667    0.402174    0.615071
            std      0.611898    0.601633    1.374883
            min      0.000000    0.000000    0.000000
            25%      0.000000    0.000000    0.000000
            50%      0.000000    0.000000    0.000000
            75%      1.000000    1.000000    1.000000
            max      3.000000    3.000000    8.000000
Parch       count  216.000000  184.000000  491.000000
            mean     0.356481    0.380435    0.393075
            std      0.693997    0.690963    0.888861
            min      0.000000    0.000000    0.000000
            25%      0.000000    0.000000    0.000000
            50%      0.000000    0.000000    0.000000
            75%      0.000000    1.000000    0.000000
            max      4.000000    3.000000    6.000000
Fare        count  216.000000  184.000000  491.000000
            mean    84.154687   20.662183   13.675550
            std     78.380373   13.417399   11.778142
            min      0.000000    0.000000    0.000000
            25%     30.923950   13.000000    7.750000
            50%     60.287500   14.250000    8.050000
            75%     93.500000   26.000000   15.500000
            max    512.329200   73.500000   69.550000

### **Sacando las estadisticas básicas de una columna**

In [111]:
precios_ticket_promedios = grouped['Fare'].mean() # sacando el precio promedio por clase
precios_ticket_promedios

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [112]:
precios_ticket_promedios = grouped['Fare'].max() # sacando el valor maximo del ticket por clase
precios_ticket_promedios

Pclass
1    512.3292
2     73.5000
3     69.5500
Name: Fare, dtype: float64

In [113]:
grouped['Fare'].quantile(.10)

Pclass
1    26.5500
2    10.5000
3     7.2292
Name: Fare, dtype: float64

### **Sacando las estadisticas con agg()**

La función agg en pandas se utiliza para aplicar funciones de agregación a grupos de datos. Permite realizar operaciones más complejas y personalizadas que las funciones predefinidas de agregación como mean, sum, etc.

**Sintaxis:**

```python
resultado_agg = df.groupby('VarCategorica').agg({'ColumnaNumerica': [lista funciones ]})

####Ejemplo funciones predefinidas ####
resultado_agg = df.groupby('VarCategorica').agg({'ColumnaNumerica': ['mean', 'median', 'sum', 'min', 'max']})

####Ejemplo funciones personalizadas ####
def mifunc():
  ###hace algun calculo

resultado_agg = df.groupby('VarCategorica').agg({'ColumnaNumerica': ['mean', mifunc]})

```

In [114]:
agregaciones_multiples = grouped.agg({'Fare': ['mean', 'min', 'max']})
agregaciones_multiples

             Fare
             mean  min       max
Pclass
1       84.154687  0.0  512.3292
2       20.662183  0.0   73.5000
3       13.675550  0.0   69.5500

In [115]:
# Forma alternativa de llamar la función agg
agregaciones_multiples = grouped['Fare'].agg([min, max, sum])
agregaciones_multiples

<ipython-input-115-ac4117b5974e>:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  agregaciones_multiples = grouped['Fare'].agg([min, max, sum])
<ipython-input-115-ac4117b5974e>:2: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  agregaciones_multiples = grouped['Fare'].agg([min, max, sum])
<ipython-input-115-ac4117b5974e>:2: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  agregaciones_multiples = grouped['Fare'].agg([min, max, sum])

        min       max         sum
Pclass
1       0.0  512.3292  18177.4125
2       0.0   73.5000   3801.8417
3       0.0   69.5500   6714.6951

In [116]:
# Aplicar múltiples funciones de agregación a la vez
# Primeros nos quedamos sin los valores 0 y luego agrupamos con groupby
agregaciones_multiples = df[df["Fare"]>0].groupby('Pclass').agg({'Fare': ['mean', 'min', 'max']})
agregaciones_multiples

             Fare
             mean      min       max
Pclass
1       86.148874   5.0000  512.3292
2       21.358661  10.5000   73.5000
3       13.787875   4.0125   69.5500

In [117]:
def rango(x):
  """
    Calcula el rango estadístico de un conjunto de datos (diferencia entre el
    valor máximo y el valor mínimo en un conjunto de datos).

    Parámetros:
    - x (pandas.Series): Serie de pandas que representa una columna de datos.

    Retorna:
    - float: El rango estadístico, es decir, la diferencia entre el valor máximo y el valor mínimo en x.
  """
  return x.max() - x.min()

In [118]:
agregaciones_multiples_prersonalizadas = grouped.agg({'Fare': ['mean', 'median', 'sum', rango]})
agregaciones_multiples_prersonalizadas

             Fare
             mean   median         sum     rango
Pclass
1       84.154687  60.2875  18177.4125  512.3292
2       20.662183  14.2500   3801.8417   73.5000
3       13.675550   8.0500   6714.6951   69.5500

###**Transformando los grupos**
El método `transform()` en groupby se utiliza para realizar operaciones de transformación en cada grupo de datos y devolver un objeto con la misma forma que el objeto original.

**Sintaxis**:

`DataFrame.groupby('clave').transform(func, *args, **kwargs)`

* **func:** Función, función anónima (lambda), o nombre de función que se aplicará a cada grupo.

### **Ejemplo de uso: Llenando los valores faltantes**

Puedes utilizar transform para llenar los valores faltantes en cada grupo con la media del grupo

In [119]:
df["Age"].isna().sum()

177

In [120]:
df['Age_faltante'] = df.groupby('Pclass')['Age'].transform(lambda x: x.fillna(x.mean()))

In [121]:
df["Age_faltante"].isna().sum()

0

### **Filtrando con filter()**

El método `filter()` en `groupby` permite filtrar grupos de datos según una condición y devolver un nuevo DataFrame que incluye solo los grupos que cumplen con esa condición.

```python
DataFrame.groupby('clave').filter(func, *args, **kwargs)

```
* **func:** Función, función anónima (**lambda**), o nombre de función que devuelve `True` o `False`.

In [122]:
# Filtrando los grupos cuyo promedio de valor de ticket es mayor a 20
filtrando_grupos =  df[df["Fare"]>0].groupby('Pclass').filter(lambda x: x['Fare'].mean()> 20)
filtrando_grupos.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_faltante
0,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,35.0
1,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,35.0

In [123]:
filtrando_grupos["Pclass"].value_counts()  # Eliminando una clase (3)

Pclass
1    211
2    178
Name: count, dtype: int64

In [124]:
df[df.Fare>0]["Pclass"].value_counts()  # Vemos que originalmente habían 3

Pclass
3    487
1    211
2    178
Name: count, dtype: int64